import yfinance as yf
import pandas as pd

tickers = {
    "ACG1V.HE": {"name": "Aallon Group Oyj", "sector": "Industrials"},
    "ADMCM.HE": {"name": "Admicom Oyj", "sector": "Technology"},
    "AFAGR.HE": {"name": "Afarak Group Oyj", "sector": "Materials"},
    "AKTIA.HE": {"name": "Aktia Bank Oyj", "sector": "Financials"},
    "ALBAV.HE": {"name": "Alma Media Oyj A", "sector": "Communication Services"},
    "ALBBV.HE": {"name": "Alma Media Oyj B", "sector": "Communication Services"},
    "ALEX.HE": {"name": "Alexandria Group Oyj", "sector": "Financials"},
    "ALISA.HE": {"name": "Alisa Pankki Oyj", "sector": "Financials"},
    "ALMA.HE": {"name": "Alma Media Oyj", "sector": "Communication Services"},
    "ANORA.HE": {"name": "Anora Group Oyj", "sector": "Consumer Staples"},
    "APETIT.HE": {"name": "Apetit Oyj", "sector": "Consumer Staples"},
    "ASPO.HE": {"name": "Aspo Oyj", "sector": "Industrials"},
    "ATRAV.HE": {"name": "Atria Oyj", "sector": "Consumer Staples"},
    "BOREO.HE": {"name": "Boreo Oyj", "sector": "Industrials"},
    "CAPMAN.HE": {"name": "CapMan Oyj", "sector": "Financials"},
    "CONSTI.HE": {"name": "Consti Oyj", "sector": "Industrials"},
    "CTH1V.HE": {"name": "Citycon Oyj", "sector": "Real Estate"},
    "DETEC.HE": {"name": "Detection Technology Oyj", "sector": "Technology"},
    "DIGIA.HE": {"name": "Digia Oyj", "sector": "Technology"},
    "DIGIGR.HE": {"name": "Digitalist Group Oyj", "sector": "Technology"},
    "EAB.HE": {"name": "EAB Group Oyj", "sector": "Financials"},
    "ELISA.HE": {"name": "Elisa Oyj", "sector": "Communication Services"},
    "ENENTO.HE": {"name": "Enento Group Oyj", "sector": "Industrials"},
    "FSKRS.HE": {"name": "Fiskars Oyj", "sector": "Consumer Discretionary"},
    "FORTUM.HE": {"name": "Fortum Oyj", "sector": "Utilities"},
    "HARVIA.HE": {"name": "Harvia Oyj", "sector": "Consumer Discretionary"},
    "HIAB.HE": {"name": "Hiab", "sector": "Industrials"},
    "HUH1V.HE": {"name": "Huhtamäki Oyj", "sector": "Materials"},
    "KALMAR.HE": {"name": "Kalmar Oyj", "sector": "Industrials"},
    "KCR.HE": {"name": "Konecranes Oyj", "sector": "Industrials"},
    "KEMIRA.HE": {"name": "Kemira Oyj", "sector": "Materials"},
    "KEMPOWR.HE": {"name": "Kempower Oyj", "sector": "Industrials"},
    "KESKOB.HE": {"name": "Kesko Oyj B", "sector": "Consumer Staples"},
    "KESKOA.HE": {"name": "Kesko Oyj A", "sector": "Consumer Staples"},
    "KELAS.HE": {"name": "Kesla Oyj", "sector": "Industrials"},
    "KNEBV.HE": {"name": "KONE Oyj", "sector": "Industrials"},
    "KOSKI.HE": {"name": "Koskisen Oyj", "sector": "Materials"},
    "KREATE.HE": {"name": "Kreate Group Oyj", "sector": "Industrials"},
    "LAPWALL.HE": {"name": "LapWall Oyj", "sector": "Materials"},
    "LOIHDE.HE": {"name": "Loihde Oyj", "sector": "Technology"},
    "METSO.HE": {"name": "Metso Oyj", "sector": "Industrials"},
    "MODU.HE": {"name": "Modulight Oyj", "sector": "Healthcare"},
    "NESTE.HE": {"name": "Neste Oyj", "sector": "Energy"},
    "NOKIA.HE": {"name": "Nokia Oyj", "sector": "Technology"},
    "TYRES.HE": {"name": "Nokian Renkaat Oyj", "sector": "Consumer Discretionary"},
    "NORRH.HE": {"name": "Nordea (check listing)", "sector": "Financials"},
    "OLVAS.HE": {"name": "Olvi Oyj", "sector": "Consumer Staples"},
    "ORNBV.HE": {"name": "Orion Oyj B", "sector": "Healthcare"},
    "ORNAV.HE": {"name": "Orion Oyj A", "sector": "Healthcare"},
    "OUT1V.HE": {"name": "Outokumpu Oyj", "sector": "Materials"},
    "PON1V.HE": {"name": "Ponsse Oyj", "sector": "Industrials"},
    "PURMO.HE": {"name": "Purmo Group Oyj", "sector": "Industrials"},
    "PUUILO.HE": {"name": "Puuilo Oyj", "sector": "Consumer Discretionary"},
    "QTCOM.HE": {"name": "Qt Group Oyj", "sector": "Technology"},
    "RAUTE.HE": {"name": "Raute Oyj", "sector": "Industrials"},
    "REMEDY.HE": {"name": "Remedy Entertainment Oyj", "sector": "Communication Services"},
    "REG1V.HE": {"name": "Revenio Group Oyj", "sector": "Healthcare"},
    "ROVIO.HE": {"name": "Rovio Entertainment Oyj", "sector": "Communication Services"},
    "SAMPO.HE": {"name": "Sampo Oyj", "sector": "Financials"},
    "SANOMA.HE": {"name": "Sanoma Oyj", "sector": "Communication Services"},
    "SCANFL.HE": {"name": "Scanfil Oyj", "sector": "Industrials"},
    "SIILI.HE": {"name": "Siili Solutions Oyj", "sector": "Technology"},
    "SOLTEQ.HE": {"name": "Solteq Oyj", "sector": "Technology"},
    "SSABAH.HE": {"name": "SSAB A", "sector": "Materials"},
    "STERV.HE": {"name": "Stora Enso Oyj R", "sector": "Materials"},
    "TAMTRON.HE": {"name": "Tamtron Oyj", "sector": "Industrials"},
    "TEM1V.HE": {"name": "Terveystalo Oyj", "sector": "Healthcare"},
    "TIETO.HE": {"name": "TietoEVRY Oyj", "sector": "Technology"},
    "TOIVO.HE": {"name": "Toivo Group Oyj", "sector": "Real Estate"},
    "TOKMAN.HE": {"name": "Tokmanni Group Oyj", "sector": "Consumer Discretionary"},
    "UPM.HE": {"name": "UPM-Kymmene Oyj", "sector": "Materials"},
    "VALOE.HE": {"name": "Valoe Oyj", "sector": "Technology"},
    "VALMT.HE": {"name": "Valmet Oyj", "sector": "Industrials"},
    "VIAFIN.HE": {"name": "Viafin Service Oyj", "sector": "Industrials"},
    "VINCIT.HE": {"name": "Vincit Oyj", "sector": "Technology"},
    "VMP.HE": {"name": "Eezy Oyj", "sector": "Industrials"},
    "WRT1V.HE": {"name": "Wärtsilä Oyj", "sector": "Industrials"},
    "WUF1V.HE": {"name": "Wulff-Yhtiöt Oyj", "sector": "Industrials"}
}